### ISSUE TITLE
transparent

### ISSUE THREAD

**Issue by strarsis** [colorjs/color-name#18]
`transparent` is a [valid color keyword in CSS](https://www.w3.org/TR/2018/REC-css-color-3-20180619/#transparent). It would be great if it is added so parsers like [postcss-values-parser](https://github.com/shellscape/postcss-values-parser/blob/master/lib/nodes/Word.js#L38) can flag it as a color.

**Comment by dy** [comment]
`transparent` is a special CSS color keyword, according to the spec, like `currentColor`. This package covers basic color keywords, without alpha channel. I can't imagine how this can be changed. The strategy of wrapping this package and extending alpha-channel and transparency keyword seems to be more reasonable, if required.
