### ISSUE TITLE
Where is v2.0.0?

### ISSUE THREAD

**Issue by matthias-ccri** [colorjs/color-name#24]
Version `2.0.0` was published in the npm registry two years ago but is nowhere to be found in this repo.

How can consumers trust that version `2.0.0` is legit?

This isn't the first time: 
- https://github.com/colorjs/color-name/issues/11
- https://github.com/colorjs/color-name/issues/15

See the [css-color-names](https://www.npmjs.com/package/css-color-names-rgb) package. That package is [verified in npm](https://www.npmjs.com/package/css-color-names-rgb), which means it's published directly from source via GitHub Actions. That publishing setup is all on GitHub, so it's possible to just copy-paste how they do it.

**Comment by dy** [comment]
Added. Thank you.

**Comment by matthias-ccri** [comment]
Thanks, good point about the bundlers, that's true.
